apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "taskflow.fullname" . }}-backend
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "taskflow.fullname" . }}-frontend
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
