apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskflow.fullname" . }}-secrets
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  TASKFLOW_SECRET_KEY: {{ .Values.global.secretKey | quote }}
  TASKFLOW_DATABASE_URL: {{ .Values.global.databaseUrl | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
