apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskflow.fullname" . }}-worker
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "taskflow.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "taskflow.fullname" . }}-config
            - secretRef:
                name: {{ include "taskflow.fullname" . }}-secrets
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - from app.cache import get_redis; get_redis().ping()
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
                - python
                - -c
                - from app.cache import get_redis; get_redis().ping()
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
