apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
type: Opaque
data:
  TASKFLOW_SECRET_KEY: ZGV2LXNlY3JldC1jaGFuZ2UtbWU=
  TASKFLOW_DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vdGFza2Zsb3c6dGFza2Zsb3dAcG9zdGdyZXM6NTQzMi90YXNrZmxvdw==
  POSTGRES_DB: dGFza2Zsb3c=
  POSTGRES_USER: dGFza2Zsb3c=
  POSTGRES_PASSWORD: dGFza2Zsb3c=
